# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Project Configuration
project.name=QSPulldownTweak
project.android.compileSdk=35
project.android.minSdk=32
project.android.targetSdk=35
project.app.packageName=me.connerowen.qspulldowntweak
project.app.versionName="0.2.2"
project.app.versionCode=4